Controllers/LoanOfficerController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc;
using System.Text.Encodings.Web;
using StudentLoanSystem.Pages.UserPages;

namespace StudentLoanSystem.Controllers
{
    public class LoanOfficerController : Controller
    {
        [HttpPost]
        public IActionResult Approve(LoanOfficerMainViewModel vm)
        {
            
            return View();
        }

        public IActionResult Index()
        {
            return View();
        }
    }
}

Pages/UserPages/LoanOfficerMainView.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Data.SqlClient;
using StudentLoanSystem.Data;

namespace StudentLoanSystem.Pages.UserPages
{
    public class LoanOfficerMainViewModel : PageModel
    {
        private readonly AccountData _context;

        public LoanOfficerMainViewModel(AccountData context)
        {
            _context = context;
            StudentDatabase = AccountData.RetrieveStudentList();
            LoanDatabase = AccountData.RetrieveLoanList();
            approved = new List<Loan>(LoanDatabase.Where(loan => loan.Approved == 1));
            denied = new List<Loan>(LoanDatabase.Where(loan => loan.Approved == 2));
            unapproved = new List<Loan>(LoanDatabase.Where(loan => loan.Approved == 0));
            ApproveArray = new string[unapproved.Count];
            RiskResult = "";
        }

        public List<StudentLoanSystem.Data.Loan> LoanDatabase { get; set; }
        public List<StudentLoanSystem.Data.Users.Student> StudentDatabase { get; set; }
        public List<Loan> approved { get; set; }
        public List<Loan> denied { get; set; }
        public List<Loan> unapproved { get; set; }
        [BindProperty]
        public int CalcCreditScore { get; set; }
        [BindProperty]
        public int CalcYearlyIncome { get; set; }
        [BindProperty]
        public int CalcAmount { get; set; }
        [BindProperty]
        public int CalcAccountBalance { get; set; }
        [BindProperty]
        public string RiskResult { get; set; }
        [BindProperty]
        public string[] ApproveArray { get; set; }

        public async Task OnGet()
        {
        }

        public async Task<IActionResult> OnPostRiskCalculateAsync()
        {
            RiskResult = StudentLoanSystem.Data.RiskCalculator.calculateRisk(CalcCreditScore, CalcYearlyIncome, CalcAmount, CalcAccountBalance).ToString();
            return Page();
        }

        public async Task<IActionResult> OnPostSubmitLoansAsync()
        {

            for (var i = 0; i < ApproveArray.Length; i++)
            {
                if (ApproveArray.ElementAt(i) == "Approve")
                {
                    this.unapproved.ElementAt(i).Approved = 1;
                }
                else if (ApproveArray.ElementAt(i) == "Deny") 
                {
                    this.unapproved.ElementAt(i).Approved = 2;
                }
            }

            SqlConnectionStringBuilder builder = new SqlConnectionStringBuilder();
            builder.DataSource = "student-loan-server.database.windows.net";
            builder.UserID = "student-loan-admin";
            builder.Password = "Password123";
            builder.InitialCatalog = "student-loan-db";

            using (SqlConnection connection = new SqlConnection(builder.ConnectionString))
            {
                connection.Open();
                String sql = "UPDATE LoanTable SET approved='1' WHERE Id=";
                foreach (var item in this.unapproved.ToList())
                {
                    if (item.Approved == 1) {
                        sql += "'" + item.Id.ToString() + "' OR Id=";
                        this.unapproved.Remove(item);
                        this.approved.Add(item);
                    }
                }
                if (sql.EndsWith("' OR Id="))
                {
                    sql = sql.Substring(0, sql.Length - 7);

                    using (SqlCommand command = new SqlCommand(sql, connection))
                    {
                        command.ExecuteNonQuery();
                    }
                }

                sql = "UPDATE LoanTable SET approved='2' WHERE Id=";
                foreach (var item in this.unapproved.ToList())
                {
                    if (item.Approved == 2)
                    {
                        sql += "'" + item.Id.ToString() + "' OR Id=";
                        this.unapproved.Remove(item);
                        this.denied.Add(item);
                    }
                }
                if (sql.EndsWith("' OR Id="))
                {
                    sql = sql.Substring(0, sql.Length - 7);

                    using (SqlCommand command = new SqlCommand(sql, connection))
                    {
                        command.ExecuteNonQuery();
                    }
                }
                connection.Close();
            }
            return Page();
        }
    }
}

Pages/UserPages/LoanOfficerView.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace StudentLoanSystem.Pages.UserPages
{
    public class LoanOfficerViewModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Pages/UserPages/RegistrarView.cshtml.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Data.SqlClient;

namespace StudentLoanSystem.Pages.Data
{
    public class RegistrarViewModel : PageModel
    {
        private readonly StudentLoanSystem.Data.AccountData _context;
        public List<StudentLoanSystem.Data.Loan> LoanDatabase { get; set; }
        public List<StudentLoanSystem.Data.Users.Student> StudentDatabase { get; set; }
        [BindProperty]
        public string StudentID { get; set; }
        [BindProperty]
        public string MessageText { get; set; }
  
        public RegistrarViewModel(StudentLoanSystem.Data.AccountData context)
        {
            _context = context;
            StudentDatabase = StudentLoanSystem.Data.AccountData.RetrieveStudentList();
            LoanDatabase = StudentLoanSystem.Data.AccountData.RetrieveLoanList();
        }
        public async Task<IActionResult> OnPostSendMessageAsync()
        {
            SqlConnectionStringBuilder builder = new SqlConnectionStringBuilder();
            builder.DataSource = "student-loan-server.database.windows.net";
            builder.UserID = "student-loan-admin";
            builder.Password = "Password123";
            builder.InitialCatalog = "student-loan-db";

            using (SqlConnection connection = new SqlConnection(builder.ConnectionString))
            {
                connection.Open();
                String sql = "INSERT INTO MessageTable (StudentID, MessageText) VALUES ('";
                sql += StudentID;
                sql += "', '";
                sql += MessageText;
                sql += "');";
                using (SqlCommand command = new SqlCommand(sql, connection))
                {
                    command.ExecuteNonQuery();
                }
                connection.Close();
            }
                
            return Page();
        }
        public void OnGet()
        {
        }
    }
}

Pages/UserPages/StudentView.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using StudentLoanSystem.Data;

namespace StudentLoanSystem.Pages.UserPages
{
    public class StudentViewModel : PageModel
    {

        //public string loanName { get; set; }

        public void OnGet()
        {
           // List<StudentLoanSystem.Data.Loan> studentLoanList = Data.AccountData.CurrentStudent.studentLoans;
           // StudentLoanSystem.Data.Loan studentLoan = studentLoanList[0];
           // loanName = studentLoan.loanName;
        }


    }
}

Pages/UserPages/LoanOfficerMainView.cshtml
@page
@model StudentLoanSystem.Pages.UserPages.LoanOfficerMainViewModel

@{
    ViewData["Title"] = "LoanOfficerMainView";

}

<h1>Loans For Review</h1>
<div>
    <form method="post">
        <table class="table">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayName("Student ID")
                    </th>
                    <th>
                        @Html.DisplayName("First Name")
                    </th>
                    <th>
                        @Html.DisplayName("Last Name")
                    </th>
                    <th>
                        @Html.DisplayName("Post Time")
                    </th>
                    <th>
                        @Html.DisplayName("Principle")
                    </th>
                    <th>
                        @Html.DisplayName("Interest Rate")
                    </th>
                    <th>
                        @Html.DisplayName("Start Date")
                    </th>
                    <th>
                        @Html.DisplayName("Length")
                    </th>
                    <th>
                        @Html.DisplayName("Approve")
                    </th>
                    <th>
                        @Html.DisplayName("Deny")
                    </th>
                </tr>
            </thead>
            <tbody>
                <div class="form-check-inline">
                    @{
                        var count = 0;
                        foreach (var item in Model.unapproved)
                        {
                            //var approve = Model.AboutToApprove[item.Id - 1];
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.StudentId)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.FirstName)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.LastName)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.PostTime)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Principle)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Rate)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Start)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Length)
                                </td>
                                <td>
                                    @Html.RadioButtonFor(modelItem => Model.ApproveArray[count], "Approve")
                                </td>
                                <td>
                                    @Html.RadioButtonFor(modelItem => Model.ApproveArray[count], "Deny")
                                </td>
                            </tr>
                            count++;
                        }
                    }
            </tbody>
        </table>
        <button asp-page-handler="SubmitLoans">Submit</button>
    </form>
</div>

<h1>Approved Loans</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayName("Student ID")
            </th>
            <th>
                @Html.DisplayName("First Name")
            </th>
            <th>
                @Html.DisplayName("Last Name")
            </th>
            <th>
                @Html.DisplayName("Post Time")
            </th>
            <th>
                @Html.DisplayName("Principle")
            </th>
            <th>
                @Html.DisplayName("Interest Rate")
            </th>
            <th>
                @Html.DisplayName("Start Date")
            </th>
            <th>
                @Html.DisplayName("Length")
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.approved)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.StudentId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FirstName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LastName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PostTime)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Principle)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Rate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Start)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Length)
                </td>
            </tr>
        }
    </tbody>
</table>

<h1>Denied Loans</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayName("Student ID")
            </th>
            <th>
                @Html.DisplayName("First Name")
            </th>
            <th>
                @Html.DisplayName("Last Name")
            </th>
            <th>
                @Html.DisplayName("Post Time")
            </th>
            <th>
                @Html.DisplayName("Principle")
            </th>
            <th>
                @Html.DisplayName("Interest Rate")
            </th>
            <th>
                @Html.DisplayName("Start Date")
            </th>
            <th>
                @Html.DisplayName("Length")
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.denied)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.StudentId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FirstName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LastName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PostTime)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Principle)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Rate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Start)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Length)
                </td>
            </tr>
        }
    </tbody>
</table>
<form method="post">
    <fieldset>
        <h1>Calculate Risk</h1>
        <div>
            @Html.DisplayName("Student Credit Score")
            @Html.TextBoxFor(modelItem => Model.CalcCreditScore)
            @Html.DisplayName("Student Yearly Income")
            @Html.TextBoxFor(modelItem => Model.CalcYearlyIncome)
            @Html.DisplayName("Loan Amount")
            @Html.TextBoxFor(modelItem => Model.CalcAmount)
            @Html.DisplayName("Student Account Balance")
            @Html.TextBoxFor(modelItem => Model.CalcAccountBalance)
        </div>
    </fieldset>
    <button style="margin:10px;" asp-page-handler="RiskCalculate">Calculate</button>
</form>

    @Html.DisplayName("Result:")
    @Html.DisplayFor(modelItem => Model.RiskResult)



<h1>Students</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayName("Student ID")
            </th>
            <th>
                @Html.DisplayName("First Name")
            </th>
            <th>
                @Html.DisplayName("Last Name")
            </th>
            <th>
                @Html.DisplayName("Credit Score")
            </th>
            <th>
                @Html.DisplayName("Phone Number")
            </th>
            <th>
                @Html.DisplayName("Email")
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.StudentDatabase)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.StudentID)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FirstName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LastName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CreditScore)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PhoneNumber)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
            </tr>
        }
    </tbody>
</table>

Pages/UserPages/LoanOfficerView.cshtml
@page "{handler?}"
@model StudentLoanSystem.Data.AccountData
@using System.Data
@{
    ViewData["Title"] = "LoanOfficer";
    @functions{

        int i = 0;
        public async Task OnPostSelectCurrentLoanAsync()
        {
            String selectedValue = Request.Form["selectedReviewLoan"];
            try
            {
                i = Int32.Parse(selectedValue) - 1;
            }
            catch (Exception e)
            {

            }
        }

        public async Task OnPostAcceptLoanAsync()
        {
            StudentLoanSystem.Data.Users.LoanOfficer loanOfficer = StudentLoanSystem.Data.AccountData.CurrentLoanOfficer;
            StudentLoanSystem.Data.Loan tempLoan = new StudentLoanSystem.Data.Loan();
            try
            {
                String selectedValue = Request.Form["selectedReviewLoanName"];
                String loanName = selectedValue.Substring(0, 5);
                loanName = loanName.Trim();
                foreach (StudentLoanSystem.Data.Loan loan in loanOfficer.LoansNeedingReview)
                {
                    if(loan.loanName.Trim().Equals(loanName))
                    {
                        tempLoan = loan;
                        break;

                    }
                }
                StudentLoanSystem.Data.AccountData.AcceptLoan(tempLoan, loanOfficer);
                RedirectToPage("UserPages/LoanOfficerView", StudentLoanSystem.Data.AccountData.CreateUser(loanOfficer.Username, loanOfficer.Id));
            }
            catch(Exception e)
            {

            }

        }
        public async Task OnPostDenyLoanAsync()
        {
            StudentLoanSystem.Data.Users.LoanOfficer loanOfficer = StudentLoanSystem.Data.AccountData.CurrentLoanOfficer;
            StudentLoanSystem.Data.Loan tempLoan = new StudentLoanSystem.Data.Loan();
            try
            {
                String selectedValue = Request.Form["selectedReviewLoanName2"];
                String loanName = selectedValue.Substring(0, 5);
                loanName = loanName.Trim();
                foreach (StudentLoanSystem.Data.Loan loan in loanOfficer.LoansNeedingReview)
                {
                    if (loan.loanName.Trim().Equals(loanName))
                    {
                        tempLoan = loan;
                        break;
                    }
                }
                StudentLoanSystem.Data.AccountData.DenyLoan(tempLoan, loanOfficer);
                RedirectToPage("UserPages/LoanOfficerView", StudentLoanSystem.Data.AccountData.CreateUser(loanOfficer.Username, loanOfficer.Id));
            }
            catch (Exception e)
            {
                System.Diagnostics.Debug.WriteLine(e);
            }
        }
        public async Task OnPostResetLoansAsync()
        {
            StudentLoanSystem.Data.AccountData.ResetDB();
        }


    }
}
<html>
<head>
    <meta name="viewport" content="width=device-width" />
</head>
<body>

    <div class="container">
        <div class="row">
            <div class="col-md-10">
                <h2>
                    Hi @Html.Label(StudentLoanSystem.Data.AccountData.CurrentLoanOfficer.FirstName, StudentLoanSystem.Data.AccountData.CurrentLoanOfficer.FirstName, new { @class = "text-danger" }) @Html.Label(StudentLoanSystem.Data.AccountData.CurrentLoanOfficer.LastName, StudentLoanSystem.Data.AccountData.CurrentLoanOfficer.LastName, new { @class = "text-danger" }) welcome back!
                </h2>
                <div class="row">
                    <div class="col-md-4">
                        <!--Profile Information-->
                        <div class="card">
                            <div class="card-body">
                                <h5 class="card-title">Profile Information for</h5>
                                <h6 class="card-subtitle mb-2 text-muted">@Html.Label(StudentLoanSystem.Data.AccountData.CurrentLoanOfficer.FirstName, StudentLoanSystem.Data.AccountData.CurrentLoanOfficer.FirstName) @Html.Label(StudentLoanSystem.Data.AccountData.CurrentLoanOfficer.LastName, StudentLoanSystem.Data.AccountData.CurrentLoanOfficer.LastName)</h6>
                                <p class="card-text">
                                    Username: @Html.Label(StudentLoanSystem.Data.AccountData.CurrentLoanOfficer.Username, StudentLoanSystem.Data.AccountData.CurrentLoanOfficer.Username, new { @class = "text-danger" }) <br />
                                    UserType: @Html.Label(StudentLoanSystem.Data.AccountData.CurrentLoanOfficer.Id.ToString(), StudentLoanSystem.Data.AccountData.CurrentLoanOfficer.Id.ToString(), new { @class = "text-danger" }) <br />
                                    Phone Number: @Html.Label(StudentLoanSystem.Data.AccountData.CurrentLoanOfficer.PhoneNumber, StudentLoanSystem.Data.AccountData.CurrentLoanOfficer.PhoneNumber, new { @class = "text-danger" }) <br />
                                    Loan Officer ID: @Html.Label(StudentLoanSystem.Data.AccountData.CurrentLoanOfficer.LoanOfficerId.ToString(), StudentLoanSystem.Data.AccountData.CurrentLoanOfficer.LoanOfficerId.ToString(), new { @class = "text-danger" }) <br />
                                    Loan Officer Email: @Html.Label(StudentLoanSystem.Data.AccountData.CurrentLoanOfficer.Email, StudentLoanSystem.Data.AccountData.CurrentLoanOfficer.Email, new { @class = "text-danger" }) <br />
                                </p>
                            </div>
                        </div>
                        <br />
                    </div>
                    <div class="col-md-6">
                        <div class="card">
                            <div class="card-body">
                                <h5 class="card-title">Loans</h5>
                                <div class="card">
                                    <div class="card-body">
                                        <!--Loans for Review-->
                                        <form asp-page-handler="SelectCurrentLoan" method="post" role="form">
                                            <div class="input-group">
                                                @Html.DropDownList(StudentLoanSystem.Data.AccountData.ReviewLoanItems.ToString(), StudentLoanSystem.Data.AccountData.ReviewLoanItems, "Loans for Review", new { @class = "form-control", @onChange = "ReviewLoanSelection(this)" })<br />
                                                <span class="input-group-btn">
                                                    <Button class="input-group-addon btn btn-default">See Loan Details</Button>
                                                </span>
                                                <input type="hidden" name="selectedReviewLoan" id="selectedReviewLoan" runat="server" />
                                            </div>
                                        </form>
                                        <br />
                                        <div class="card">
                                            <div class="card-body">
                                                @Html.Label(StudentLoanSystem.Data.AccountData.CurrentLoanOfficer.LoansNeedingReview[i].loanName, StudentLoanSystem.Data.AccountData.CurrentLoanOfficer.LoansNeedingReview[i].loanName, new { @class = "text-danger" }) <br />
                                                Student Applying: @Html.Label(StudentLoanSystem.Data.AccountData.CurrentLoanOfficer.LoansNeedingReview[i].firstName, StudentLoanSystem.Data.AccountData.CurrentLoanOfficer.LoansNeedingReview[i].firstName, new { @class = "text-danger" }) @Html.Label(StudentLoanSystem.Data.AccountData.CurrentLoanOfficer.LoansNeedingReview[i].lastName, StudentLoanSystem.Data.AccountData.CurrentLoanOfficer.LoansNeedingReview[i].lastName, new { @class = "text-danger" })<br />
                                                Credit Score: @Html.Label(StudentLoanSystem.Data.AccountData.CurrentLoanOfficer.LoansNeedingReview[i].creditScore.ToString(), StudentLoanSystem.Data.AccountData.CurrentLoanOfficer.LoansNeedingReview[i].creditScore.ToString(), new { @class = "text-danger" }) <br />
                                                Student ID: @Html.Label(StudentLoanSystem.Data.AccountData.CurrentLoanOfficer.LoansNeedingReview[i].studentId.ToString(), StudentLoanSystem.Data.AccountData.CurrentLoanOfficer.LoansNeedingReview[i].studentId.ToString(), new { @class = "text-danger" }) <br />
                                                Principle: @Html.Label(StudentLoanSystem.Data.AccountData.CurrentLoanOfficer.LoansNeedingReview[i].principle.ToString(), StudentLoanSystem.Data.AccountData.CurrentLoanOfficer.LoansNeedingReview[i].principle.ToString(), new { @class = "text-danger" }) <br />
                                                Start Date: @Html.Label(StudentLoanSystem.Data.AccountData.CurrentLoanOfficer.LoansNeedingReview[i].start.ToString(), StudentLoanSystem.Data.AccountData.CurrentLoanOfficer.LoansNeedingReview[i].start.ToString(), new { @class = "text-danger" }) <br />
                                                Date Posted: @Html.Label(StudentLoanSystem.Data.AccountData.CurrentLoanOfficer.LoansNeedingReview[i].postTime.ToString(), StudentLoanSystem.Data.AccountData.CurrentLoanOfficer.LoansNeedingReview[i].postTime.ToString(), new { @class = "text-danger" }) <br />
                                            </div>
                                        </div>
                                        <br />
                                        <div class="row">
                                            <div class="col-md-6">
                                                <form asp-page-handler="AcceptLoan" method="post" role="form">
                                                    <input class="btn btn-success" type="submit" value="Accept Loan" onchange="ReviewLoanSelection(this)">
                                                    <input type="hidden" name="selectedReviewLoanName" id="selectedReviewLoanName" runat="server" />
                                                </form>
                                            </div>
                                            <div class="col-md-6">
                                                <form asp-page-handler="DenyLoan" method="post" role="form">
                                                    <input class="btn btn-danger" type="submit" value="Deny Loan" onchange="ReviewLoanSelection(this)">
                                                    <input type="hidden" name="selectedReviewLoanName2" id="selectedReviewLoanName2" runat="server" />
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <script>
                        function ReviewLoanSelection(ddlObject) {
                            var selectedIndex = ddlObject.selectedIndex
                            var selectedText = ddlObject.options[ddlObject.selectedIndex].innerHTML;
                            var hiddenField = document.getElementById('selectedReviewLoan');
                            var hiddenField2 = document.getElementById('selectedReviewLoanName');
                            var hiddenField3 = document.getElementById('selectedReviewLoanName2')
                            hiddenField.value = selectedIndex;
                            hiddenField2.value = selectedText;
                            hiddenField3.value = selectedText;
                        }
                    </script>
                </div>
            </div>
            <div class="col-md-2">
                <div class="row">
                    <a class="nav-link text-dark" asp-area="" asp-page="/Index"><button type="button" class="btn btn-danger">Logout?</button></a>
                </div>
                <div class="row">
                    <form asp-page-handler="ResetLoans" method="post" role="form">
                        <input class="btn btn-success" type="submit" value="Master Reset DB">
                    </form>
                </div>
            </div>
        </div>
    </div>

 </body>
</html>